services:
  - type: web
    name: trading-signals-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: YOUR_WALLET
        value: 0xA6B72E65d66B4BaDa4D3c835278D74c6403A8616
      - key: ACCESS_DURATION
        value: "3092000"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false

  - type: cron
    name: signal-payment-worker
    env: python
    schedule: "*/5 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: YOUR_WALLET
        value: 0xA6B72E65d66B4BaDa4D3c835278D74c6403A8616
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
